apiVersion: v1
kind: Service
metadata:
  name: {{ include "portage.fullname" . }}-api
  labels:
    {{- include "portage.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "portage.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
