{{- if .Values.reconciler.inClusterKubeconfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portage.fullname" . }}-reconciler-kubeconfig
  labels:
    {{- include "portage.labels" . | nindent 4 }}
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: in-cluster
        cluster:
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          server: https://kubernetes.default.svc
    contexts:
      - name: in-cluster
        context:
          cluster: in-cluster
          user: in-cluster
    current-context: in-cluster
    users:
      - name: in-cluster
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
{{- end }}
