{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portage.fullname" . }}-api
  labels:
    {{- include "portage.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portage.fullname" . }}-reconciler
  labels:
    {{- include "portage.labels" . | nindent 4 }}
    app.kubernetes.io/component: reconciler
{{- end }}
